# PRs shell check

name: pr-shell-check

on:

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: shellcheck version
        run: shellcheck --version

      - name: ls
